name: UC_Stretcher
description: camera looking at stretcher input
bit_depth: 16
roi:
  x_min: 75
  x_max: 425
  y_min: 50
  y_max: 350
background: null
crosshair_masking: null
circular_mask: null
vignette: null
thresholding: null
filtering:
  gaussian_sigma: null
  median_kernel_size: null
normalization: null
transforms:
  rotation_angle: 0.0
  flip_horizontal: false
  flip_vertical: false
  distortion_correction: false
  distortion_coeffs: null
pipeline:
  steps:
  - roi
  - filtering
  - transforms
analysis: null
